name: myApp
description: A new Flutter project.
publish_to: 'none'
version: 2.0.3+5

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  upgrader: ^8.4.0
  new_version_plus: ^0.0.10
  app_version_update: ^4.0.1
  url_launcher: ^6.2.4
  logger: ^2.1.0
  in_app_update: ^4.2.2
  http: ^0.13.6
  flutter_login: ^4.2.1
  oauth2: ^2.0.2
  fluttertoast: ^8.2.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  settings_ui: ^2.0.2
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  form_field_validator: ^1.1.0

flutter_icons:
  ios: true
  image_path: "img/origami.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
