// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyGBtq1XKmZ874Wt2YQJXuf362zBktrew',
    appId: '1:146290939716:web:67362099d02acf8efaa911',
    messagingSenderId: '146290939716',
    projectId: 'tyrsi-213fb',
    authDomain: 'tyrsi-213fb.firebaseapp.com',
    storageBucket: 'tyrsi-213fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDER-VdY5knXh7VM_zwUy28CkgW1a61MbM',
    appId: '1:146290939716:android:f5fa07b890721048faa911',
    messagingSenderId: '146290939716',
    projectId: 'tyrsi-213fb',
    storageBucket: 'tyrsi-213fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc-qU9c8ADcysvzCU1B5Am0anNQRdg_JE',
    appId: '1:146290939716:ios:bc6b62a21a7911e9faa911',
    messagingSenderId: '146290939716',
    projectId: 'tyrsi-213fb',
    storageBucket: 'tyrsi-213fb.appspot.com',
    iosBundleId: 'com.golf.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc-qU9c8ADcysvzCU1B5Am0anNQRdg_JE',
    appId: '1:146290939716:ios:c593f4bb3f2ece11faa911',
    messagingSenderId: '146290939716',
    projectId: 'tyrsi-213fb',
    storageBucket: 'tyrsi-213fb.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyGBtq1XKmZ874Wt2YQJXuf362zBktrew',
    appId: '1:146290939716:web:830e10144fbb97f7faa911',
    messagingSenderId: '146290939716',
    projectId: 'tyrsi-213fb',
    authDomain: 'tyrsi-213fb.firebaseapp.com',
    storageBucket: 'tyrsi-213fb.appspot.com',
  );

}